### ISSUE TITLE
Rerun Ev-Seg tensorflow version

### ISSUE THREAD

**Issue by lixinqi98** [lixinqi98/EV-SegNet#2]

**Comment by MTCXin** [comment]
TensorFlow version successfully run:
![image](https://user-images.githubusercontent.com/63448990/154969454-f801a4f4-5f66-469f-b442-84cbc1bb83ce.png)

**Comment by MTCXin** [comment]
I think the default data is "50ms" indicated in table2, and the model has yet achieved performence rather close to that showed in the paper(acc:87.7%/89.76%  miou:50.00/54.81) with 22 epochs of training. (the default training epoch in the code is 500, but on RTX2080Ti the training speed is 1.3epoch/h)

The original source code is Python2.7 ver , since  pip no longer support to install package for Python2 , I modified some code and get it run on Python3.6, which I think would cause no impact on the result

**Comment by MTCXin** [comment]
![image](https://user-images.githubusercontent.com/63448990/154971601-86bb74d4-93e5-4c0b-b239-476300f24672.png)
On batchsize 8(default) the code reported 'GPU out of memory' at the begining but it continued runing anyway, don't know if it would cause some problem

**Comment by lixinqi98** [comment]
> On batchsize 8(default) the code reported 'GPU out of memory' at the begining but it continued runing anyway, don't know if it would cause some problem

Guess no effect with the result. But maybe use `CUDA_VISIBLE_DEVICES` to specify the cuda device with enough memory if the cluster has multiply

**Comment by MTCXin** [comment]
> > On batchsize 8(default) the code reported 'GPU out of memory' at the begining but it continued runing anyway, don't know if it would cause some problem
> 
> Guess no effect with the result. But maybe use `CUDA_VISIBLE_DEVICES` to specify the cuda device with enough memory if the cluster has multiply

Actually the code only support single GPU training and I've used 'os.CUDA_VISIBLE_DEVICES' to specify the index of GPU to use.  Btw, It's trained on a GPU server back in THU and it used the full dataset (30G).
More info:
when specify batchsize=4: no warning
when specify batchsize=8: out of memory error but the training continued
when specify batchsize=16: out of memory error and the processing collapsed
